name: smartuaqyt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2
  connectivity_plus: ^4.0.1
  path_provider: ^2.1.2
  uuid: ^4.3.3
  intl: any

  provider: ^6.0.5
  flutter_gen_runner: ^5.4.0

  firebase_core: ^2.31.1
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
