// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChATLH1pVwOe1ycJQ5sGo2pkzUmfsrKfg',
    appId: '1:471246174606:web:025096b8b59d9617e84cdf',
    messagingSenderId: '471246174606',
    projectId: 'smartuaqyt-app',
    authDomain: 'smartuaqyt-app.firebaseapp.com',
    storageBucket: 'smartuaqyt-app.firebasestorage.app',
    measurementId: 'G-WS96FC7BME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfHwqCw-eD1n35Ng1iTOMaL6ofQhCk0YA',
    appId: '1:471246174606:android:22cc7d8e79e565a6e84cdf',
    messagingSenderId: '471246174606',
    projectId: 'smartuaqyt-app',
    storageBucket: 'smartuaqyt-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3n3Arprec74CWUtNtbEjfik-pZ7nFvnM',
    appId: '1:471246174606:ios:8b716578645ababce84cdf',
    messagingSenderId: '471246174606',
    projectId: 'smartuaqyt-app',
    storageBucket: 'smartuaqyt-app.firebasestorage.app',
    iosBundleId: 'com.example.stopwatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3n3Arprec74CWUtNtbEjfik-pZ7nFvnM',
    appId: '1:471246174606:ios:8b716578645ababce84cdf',
    messagingSenderId: '471246174606',
    projectId: 'smartuaqyt-app',
    storageBucket: 'smartuaqyt-app.firebasestorage.app',
    iosBundleId: 'com.example.stopwatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChATLH1pVwOe1ycJQ5sGo2pkzUmfsrKfg',
    appId: '1:471246174606:web:75f870468bddf9c0e84cdf',
    messagingSenderId: '471246174606',
    projectId: 'smartuaqyt-app',
    authDomain: 'smartuaqyt-app.firebaseapp.com',
    storageBucket: 'smartuaqyt-app.firebasestorage.app',
    measurementId: 'G-Q650HQVXN7',
  );
}
